### ISSUE TITLE
[Transform\EntityPopulator\RedmineApiException] : The entity could not be persisted

### ISSUE THREAD

**Issue by wildudu** [juanmf/RedmineIssueImporter#9]
Hi,

I'm testing the tool : the connection is ok (the delete command work well), but with the imort command, I've this error message: 

[Transform\EntityPopulator\RedmineApiException]   The entity could not be persisted

and Nothing about this on the web.

Can you help me ? I need a commnad-line program to create/update redmine issues each night.
Thanks in advance.

Here is my config.yml: (just to test the issue creation)
###### 
# Run customization
###### 

redmine_account:
  # http://www.redmine.org/projects/redmine/wiki/Rest_api#Authentication # show API Key.
  api_key: '89c2a68ebd4f433aca473bbd71c8c35bcb7fec5c' # siup
  host: 'http://localhost/'

input_format:
  file_type: 'Csv' # maps to CsvSheetRecordParser
  delimiter: ';'   # field delimiter
# false Makes everithing but call save on entities, for tests before hitting API

save_records: true 
###### 
# Sheets mapping configuration
###### 

on_error:
  behavior: stop # [continue, stop, rollback]
  display_exceptions: true # [true | false]

custom_fields: # redmine custom fields settings <objectType> => <customFieldName> => id => <idValue>
  issue: 
    test_nouveau_champ: 
     id: 1 # pour test champ perso

sheets:  
  #1st sheet definition
  taches:  
    name: LOCPRO
    persistence_engine: redmine
    records:
      kiloutou:
        name: tache
        project_id: kiloutou-sa
        entities:
          Issue:
            defaults:
              status: Ouverte
              priority: Normal
              tracker: Evolutions
              subject: 'Sans'
              author: 'wdurand'

```
    fields:     
      subject:
        model: {entity: 'Issue', column: 'subject'} # entity referencia entities[entity] no al schema. Para eso está entities[entity][schema_entity], en caso de que difiera.
        coord: {x: 0, y: 1}
        default: ~ # Si !== ~ pisa al default del schema y al default en [entities]
        increment: {x: 0, y: 1}  # ~ = {x: 0, y: 0} if field is recurrent increment determines the relative loction of the next sibling. ~ means the field is no recurrent, only appears once in a sheet-
        transform: ~ # a callback method
```
